esphome:
  name: big-battery-metter

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "gO9tnhGrOrwebhXUVRHe21v7Ux7MqmEhRrf1p/syEv0="

ota:
  password: "2483263699388e81cb32dba7de29d24a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Big-Battery-Metter"
    password: "HVMlMLOn8BUY"

captive_portal:
    
sensor:
  - platform: adc
    pin: A0
    name: "Voltage"
    update_interval: 5s
    filters:
      - multiply: 18.41