esphome:
  name: childroom-controller
  friendly_name: Childroom Controller

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "KhHHbJH5i9kKVQEmdJYxjRm3S1IEkleIliDZsb4kzLs="

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Bcb4F0"
    password: "QnzXD7qawEpC"

captive_portal:
    
i2c:
  sda: 4
  scl: 15
  scan: true
  id: bus_a

pcf8574:
  - id: 'pcf8574_hub_out'
    address: 0x24
  - id: 'pcf8574_hub_in'
    address: 0x22


# RS485 UART defined for CWT-TH01S sensor
uart:
  - id: 'UART_RS232'
    tx_pin: GPIO17    
    rx_pin: GPIO16
    baud_rate: 9600 
  - id: 'UART_RS485'
    tx_pin: GPIO27    
    rx_pin: GPIO14
    baud_rate: 4800

# modbus:
#   - id: 'modbus_hub'
#     uart_id: UART_RS485

# modbus_controller:
#   - id: 'temperature_humidity_sensor'
#     modbus_id: modbus_hub
#     address: 1
#     update_interval: 5s

# sensor:
#   - platform: modbus_controller
#     modbus_controller_id: temperature_humidity_sensor
#     id: temperature
#     register_type: read
#     address: 0x0001
#     name: "Temperature"
#     value_type: U_WORD
#     unit_of_measurement: "°C"
#     accuracy_decimals: 1
#     filters:
#       - multiply: 0.1
#   - platform: modbus_controller
#     modbus_controller_id: temperature_humidity_sensor
#     id: humidity
#     register_type: read
#     address: 0x0000
#     name: "Humidity"
#     unit_of_measurement: "%"
#     accuracy_decimals: 1
#     value_type: U_WORD
#     filters:
#       - multiply: 0.1

# Individual outputs
switch:
  - platform: gpio
    id: main_light
    name: "Main light"
    restore_mode: RESTORE_DEFAULT_OFF
    pin:
      pcf8574: pcf8574_hub_out
      number: 0
      mode:
        output: true
      inverted: true
  - platform: gpio
    id: spot_light
    name: "Spot light"
    restore_mode: RESTORE_DEFAULT_OFF
    pin:
      pcf8574: pcf8574_hub_out
      number: 1
      mode:
        output: true
      inverted: true
  - platform: gpio
    id: wall_panel
    name: "Wall Panel"
    restore_mode: ALWAYS_ON
    pin:
      pcf8574: pcf8574_hub_out
      number: 2
      mode:
        output: true
      inverted: true
  - platform: gpio
    id: sockets
    name: "Sockets"
    restore_mode: ALWAYS_ON
    pin:
      pcf8574: pcf8574_hub_out
      number: 3
      mode:
        output: true
      inverted: true
  - platform: gpio
    id: air_conditioner
    name: "Air Conditioner"
    restore_mode: ALWAYS_ON
    pin:
      pcf8574: pcf8574_hub_out
      number: 4
      mode:
        output: true
      inverted: true

# Individual inputs
binary_sensor:
  - platform: gpio
    id: mian_light_switch
    name: "Main light Switch"
    pin:
      pcf8574: pcf8574_hub_in
      # Use pin number 0
      number: 0
      # One of INPUT or OUTPUT
      mode:
        input: true
      inverted: true
    on_state:
      then:
        - switch.toggle: main_light
  - platform: gpio
    id: spot_light_switch
    name: "Spot light Switch"
    pin:
      pcf8574: pcf8574_hub_in
      # Use pin number 0
      number: 1
      # One of INPUT or OUTPUT
      mode:
        input: true
      inverted: true
    on_state:
      then:
        - switch.toggle: spot_light        