esphome:
  name: grid-power-check

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "W9sYDSL6iQqSwDoMZ1cJ/p8DONVwxxOPKrNobf1AEpQ="

ota:
  password: "ac97bd3bd928b8bb81bfe05f28958afa"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Grid-Power-Check"
    password: "ZN8jrT7O3CfZ"

captive_portal:

sensor:
  - platform: adc
    pin: A0
    name: "Power grid status"
    update_interval: 5s
