esphome:
  name: esphome-web-17f794
  friendly_name: test-esp-switch

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "7pDAXIZ8QL3ZyHttUEL6lZ9Kl5prtp/POc+qU5r6dDE="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-17F794"
    password: "bs552ffW7YtD"

switch:
  platform: gpio
  name: "Test ESP Switch"
  pin: 21
  id: relay
  icon: "mdi:light-switch"
  # restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin: 
      number: 19
      inverted: true
    name: "Switch"
    on_click:
      min_length: 30ms
      then:
        - switch.toggle: relay

number:
  - platform: template
    id: power_level
    name: "Power Level"
    min_value: 0
    max_value: 100
    step: 1
    icon: "mdi:power-plug"
    optimistic: true
    initial_value: 100
    restore_value: true
    on_value:
      then:
        - output.set_level:
            id: power_output
            level: !lambda 'return x / 100.0;'

output:
  - platform: ledc
    pin: 18
    id: power_output

light:
  - platform: monochromatic
    name: "Power Level"
    output: power_output
    id: power_level_light

captive_portal:
