esphome:
  name: esphome-web-17f794
  friendly_name: test-esp-switch

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "7pDAXIZ8QL3ZyHttUEL6lZ9Kl5prtp/POc+qU5r6dDE="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-17F794"
    password: "bs552ffW7YtD"

switch:
  platform: gpio
  name: "Test ESP Switch"
  pin: 21
  id: relay
  icon: "mdi:light-switch"
  on_turn_on:
    - delay: 200ms
    - switch.turn_off: relay

sensor:
  - platform: adc
    pin: 34
    name: "Test ESP Current"
    unit_of_measurement: "A"
    icon: "mdi:current-ac"
    update_interval: 5s
    attenuation: 11db
    filters:
      # empricially determined offset to match the current meter
      - offset: -1.69
      # this is 20A meter, so 20A = 1.66V, so multiplier is 20/1.66
      - multiply: 12

binary_sensor:
  - platform: gpio
    icon: "mdi:flash"
    name: "Test ESP Switch State"
    pin:
      number: 19
      mode: INPUT_PULLUP
      inverted: True

captive_portal:
